module.exports = {
  purge: {
    enabled: true,
    content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
    spacing: {
      0: '0rem',
      1: '0.1rem',
      2: '0.2rem',
      4: '0.4rem',
      6: '0.6rem',
      8: '0.8rem',
      10: '1.0rem',
      12: '1.2rem',
      14: '1.4rem',
      16: '1.6rem',
      18: '1.8rem',
      20: '2.0rem',
      22: '2.2rem',
      24: '2.4rem',
      26: '2.6rem',
      28: '2.8rem',
      30: '3.0rem',
      32: '3.2rem',
      34: '3.4rem',
      36: '3.6rem',
      38: '3.8rem',
      40: '4.0rem',
      42: '4.2rem',
      44: '4.4rem',
      46: '4.6rem',
      48: '4.8rem',
      50: '5.0rem',
      56: '5.6rem',
      /* Below values from tailwind */
      64: '6.4rem',
      80: '8.0rem',
      96: '9.6rem',
      128: '12.8rem',
      160: '16.0rem',
      192: '19.2rem',
      224: '22.4rem',
      256: '25.6rem',
    },
  },
  variants: {
    backgroundColor: ['responsive', 'hover', 'focus', 'active', 'focus-within'],
    borderColor: [
      'responsive',
      'group-hover',
      'group-focus',
      'hover',
      'focus',
      'active',
      'focus-within',
    ],
    margin: ['responsive', 'last'],
    padding: ['responsive', 'last'],
    borderRadius: ['responsive', 'hover', 'focus', 'group-hover', 'focus-within'],
    borderWidth: ['responsive', 'hover', 'focus', 'group-hover', 'last'],
    display: ['responsive', 'hover', 'focus', 'group-hover'],
    opacity: ['responsive', 'hover', 'focus', 'disabled', 'group-hover'],
    textColor: ['responsive', 'hover', 'focus', 'active', 'disabled', 'group-hover', 'group-focus'],
    textDecoration: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
  },
  plugins: [],
};
